/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComercialRouteImport } from './routes/_comercial'
import { Route as SuporteRouteImport } from './routes/_suporte'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModulosRouteImport } from './routes/modulos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ComercialAgendaRouteImport } from './routes/_comercial.agenda'
import { Route as ComercialConfiguracoesRouteImport } from './routes/_comercial.configuracoes'
import { Route as ComercialContatosRouteImport } from './routes/_comercial.contatos'
import { Route as ComercialConvitesRouteImport } from './routes/_comercial.convites'
import { Route as ComercialDashboardRouteImport } from './routes/_comercial.dashboard'
import { Route as ComercialHistoricoRouteImport } from './routes/_comercial.historico'
import { Route as ComercialOrcamentoAvulsoRouteImport } from './routes/_comercial.orcamento-avulso'
import { Route as ComercialPipelineRouteImport } from './routes/_comercial.pipeline'
import { Route as ComercialRelatoriosRouteImport } from './routes/_comercial.relatorios'
import { Route as ComercialUsuariosConfigRouteImport } from './routes/_comercial.usuarios-config'
import { Route as SuporteAjustesRouteImport } from './routes/_suporte.ajustes'
import { Route as SuporteChamadosRouteImport } from './routes/_suporte.chamados'
import { Route as SuporteMetricasRouteImport } from './routes/_suporte.metricas'
import { Route as SuportePainelRouteImport } from './routes/_suporte.painel'
import { Route as SuportePendenciasRouteImport } from './routes/_suporte.pendencias'
import { Route as SuporteRotinasRouteImport } from './routes/_suporte.rotinas'
import { Route as QuestionarioIdRouteImport } from './routes/questionario.$id'
import { Route as ComercialDiagnosticosIndexRouteImport } from './routes/_comercial.diagnosticos.index'
import { Route as ComercialDiagnosticosIdRouteImport } from './routes/_comercial.diagnosticos.$id'
import { Route as ComercialEmpresasIndexRouteImport } from './routes/_comercial.empresas.index'
import { Route as ComercialEmpresasIdRouteImport } from './routes/_comercial.empresas.$id'
import { Route as ComercialLeadsIndexRouteImport } from './routes/_comercial.leads.index'
import { Route as ComercialPropostaIdRouteImport } from './routes/_comercial.proposta.$id'
import { Route as SuporteCadastrosModulosErosRouteImport } from './routes/_suporte.cadastros.modulos-eros'
import { Route as SuporteCadastrosModulosVenuxRouteImport } from './routes/_suporte.cadastros.modulos-venux'
import { Route as SuporteCadastrosSetoresRouteImport } from './routes/_suporte.cadastros.setores'
import { Route as SuporteCadastrosTicketsRouteImport } from './routes/_suporte.cadastros.tickets'
import { Route as SuporteClientesIndexRouteImport } from './routes/_suporte.clientes.index'
import { Route as SuporteClientesIdRouteImport } from './routes/_suporte.clientes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialRoute = ComercialRouteImport.update({
  id: '/_comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/_suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosRoute = ModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialAgendaRoute = ComercialAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => ComercialRoute,
} as any)
const ComercialConfiguracoesRoute = ComercialConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => ComercialRoute,
} as any)
const ComercialContatosRoute = ComercialContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => ComercialRoute,
} as any)
const ComercialConvitesRoute = ComercialConvitesRouteImport.update({
  id: '/convites',
  path: '/convites',
  getParentRoute: () => ComercialRoute,
} as any)
const ComercialDashboardRoute = ComercialDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ComercialRoute,
} as any)
const ComercialHistoricoRoute = ComercialHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => ComercialRoute,
} as any)
const ComercialOrcamentoAvulsoRoute =
  ComercialOrcamentoAvulsoRouteImport.update({
    id: '/orcamento-avulso',
    path: '/orcamento-avulso',
    getParentRoute: () => ComercialRoute,
  } as any)
const ComercialPipelineRoute = ComercialPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => ComercialRoute,
} as any)
const ComercialRelatoriosRoute = ComercialRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => ComercialRoute,
} as any)
const ComercialUsuariosConfigRoute = ComercialUsuariosConfigRouteImport.update({
  id: '/usuarios-config',
  path: '/usuarios-config',
  getParentRoute: () => ComercialRoute,
} as any)
const SuporteAjustesRoute = SuporteAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => SuporteRoute,
} as any)
const SuporteChamadosRoute = SuporteChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => SuporteRoute,
} as any)
const SuporteMetricasRoute = SuporteMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => SuporteRoute,
} as any)
const SuportePainelRoute = SuportePainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => SuporteRoute,
} as any)
const SuportePendenciasRoute = SuportePendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => SuporteRoute,
} as any)
const SuporteRotinasRoute = SuporteRotinasRouteImport.update({
  id: '/rotinas',
  path: '/rotinas',
  getParentRoute: () => SuporteRoute,
} as any)
const QuestionarioIdRoute = QuestionarioIdRouteImport.update({
  id: '/questionario/$id',
  path: '/questionario/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialDiagnosticosIndexRoute =
  ComercialDiagnosticosIndexRouteImport.update({
    id: '/diagnosticos/',
    path: '/diagnosticos/',
    getParentRoute: () => ComercialRoute,
  } as any)
const ComercialDiagnosticosIdRoute = ComercialDiagnosticosIdRouteImport.update({
  id: '/diagnosticos/$id',
  path: '/diagnosticos/$id',
  getParentRoute: () => ComercialRoute,
} as any)
const ComercialEmpresasIndexRoute = ComercialEmpresasIndexRouteImport.update({
  id: '/empresas/',
  path: '/empresas/',
  getParentRoute: () => ComercialRoute,
} as any)
const ComercialEmpresasIdRoute = ComercialEmpresasIdRouteImport.update({
  id: '/empresas/$id',
  path: '/empresas/$id',
  getParentRoute: () => ComercialRoute,
} as any)
const ComercialLeadsIndexRoute = ComercialLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => ComercialRoute,
} as any)
const ComercialPropostaIdRoute = ComercialPropostaIdRouteImport.update({
  id: '/proposta/$id',
  path: '/proposta/$id',
  getParentRoute: () => ComercialRoute,
} as any)
const SuporteCadastrosModulosErosRoute =
  SuporteCadastrosModulosErosRouteImport.update({
    id: '/cadastros/modulos-eros',
    path: '/cadastros/modulos-eros',
    getParentRoute: () => SuporteRoute,
  } as any)
const SuporteCadastrosModulosVenuxRoute =
  SuporteCadastrosModulosVenuxRouteImport.update({
    id: '/cadastros/modulos-venux',
    path: '/cadastros/modulos-venux',
    getParentRoute: () => SuporteRoute,
  } as any)
const SuporteCadastrosSetoresRoute = SuporteCadastrosSetoresRouteImport.update({
  id: '/cadastros/setores',
  path: '/cadastros/setores',
  getParentRoute: () => SuporteRoute,
} as any)
const SuporteCadastrosTicketsRoute = SuporteCadastrosTicketsRouteImport.update({
  id: '/cadastros/tickets',
  path: '/cadastros/tickets',
  getParentRoute: () => SuporteRoute,
} as any)
const SuporteClientesIndexRoute = SuporteClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => SuporteRoute,
} as any)
const SuporteClientesIdRoute = SuporteClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => SuporteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/modulos': typeof ModulosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/register': typeof RegisterRoute
  '/termos': typeof TermosRoute
  '/agenda': typeof ComercialAgendaRoute
  '/configuracoes': typeof ComercialConfiguracoesRoute
  '/contatos': typeof ComercialContatosRoute
  '/convites': typeof ComercialConvitesRoute
  '/dashboard': typeof ComercialDashboardRoute
  '/historico': typeof ComercialHistoricoRoute
  '/orcamento-avulso': typeof ComercialOrcamentoAvulsoRoute
  '/pipeline': typeof ComercialPipelineRoute
  '/relatorios': typeof ComercialRelatoriosRoute
  '/usuarios-config': typeof ComercialUsuariosConfigRoute
  '/ajustes': typeof SuporteAjustesRoute
  '/chamados': typeof SuporteChamadosRoute
  '/metricas': typeof SuporteMetricasRoute
  '/painel': typeof SuportePainelRoute
  '/pendencias': typeof SuportePendenciasRoute
  '/rotinas': typeof SuporteRotinasRoute
  '/questionario/$id': typeof QuestionarioIdRoute
  '/diagnosticos/$id': typeof ComercialDiagnosticosIdRoute
  '/empresas/$id': typeof ComercialEmpresasIdRoute
  '/proposta/$id': typeof ComercialPropostaIdRoute
  '/cadastros/modulos-eros': typeof SuporteCadastrosModulosErosRoute
  '/cadastros/modulos-venux': typeof SuporteCadastrosModulosVenuxRoute
  '/cadastros/setores': typeof SuporteCadastrosSetoresRoute
  '/cadastros/tickets': typeof SuporteCadastrosTicketsRoute
  '/clientes/$id': typeof SuporteClientesIdRoute
  '/diagnosticos/': typeof ComercialDiagnosticosIndexRoute
  '/empresas/': typeof ComercialEmpresasIndexRoute
  '/leads/': typeof ComercialLeadsIndexRoute
  '/clientes/': typeof SuporteClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/modulos': typeof ModulosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/register': typeof RegisterRoute
  '/termos': typeof TermosRoute
  '/agenda': typeof ComercialAgendaRoute
  '/configuracoes': typeof ComercialConfiguracoesRoute
  '/contatos': typeof ComercialContatosRoute
  '/convites': typeof ComercialConvitesRoute
  '/dashboard': typeof ComercialDashboardRoute
  '/historico': typeof ComercialHistoricoRoute
  '/orcamento-avulso': typeof ComercialOrcamentoAvulsoRoute
  '/pipeline': typeof ComercialPipelineRoute
  '/relatorios': typeof ComercialRelatoriosRoute
  '/usuarios-config': typeof ComercialUsuariosConfigRoute
  '/ajustes': typeof SuporteAjustesRoute
  '/chamados': typeof SuporteChamadosRoute
  '/metricas': typeof SuporteMetricasRoute
  '/painel': typeof SuportePainelRoute
  '/pendencias': typeof SuportePendenciasRoute
  '/rotinas': typeof SuporteRotinasRoute
  '/questionario/$id': typeof QuestionarioIdRoute
  '/diagnosticos/$id': typeof ComercialDiagnosticosIdRoute
  '/empresas/$id': typeof ComercialEmpresasIdRoute
  '/proposta/$id': typeof ComercialPropostaIdRoute
  '/cadastros/modulos-eros': typeof SuporteCadastrosModulosErosRoute
  '/cadastros/modulos-venux': typeof SuporteCadastrosModulosVenuxRoute
  '/cadastros/setores': typeof SuporteCadastrosSetoresRoute
  '/cadastros/tickets': typeof SuporteCadastrosTicketsRoute
  '/clientes/$id': typeof SuporteClientesIdRoute
  '/diagnosticos': typeof ComercialDiagnosticosIndexRoute
  '/empresas': typeof ComercialEmpresasIndexRoute
  '/leads': typeof ComercialLeadsIndexRoute
  '/clientes': typeof SuporteClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_comercial': typeof ComercialRouteWithChildren
  '/_suporte': typeof SuporteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/modulos': typeof ModulosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/register': typeof RegisterRoute
  '/termos': typeof TermosRoute
  '/_comercial/agenda': typeof ComercialAgendaRoute
  '/_comercial/configuracoes': typeof ComercialConfiguracoesRoute
  '/_comercial/contatos': typeof ComercialContatosRoute
  '/_comercial/convites': typeof ComercialConvitesRoute
  '/_comercial/dashboard': typeof ComercialDashboardRoute
  '/_comercial/historico': typeof ComercialHistoricoRoute
  '/_comercial/orcamento-avulso': typeof ComercialOrcamentoAvulsoRoute
  '/_comercial/pipeline': typeof ComercialPipelineRoute
  '/_comercial/relatorios': typeof ComercialRelatoriosRoute
  '/_comercial/usuarios-config': typeof ComercialUsuariosConfigRoute
  '/_suporte/ajustes': typeof SuporteAjustesRoute
  '/_suporte/chamados': typeof SuporteChamadosRoute
  '/_suporte/metricas': typeof SuporteMetricasRoute
  '/_suporte/painel': typeof SuportePainelRoute
  '/_suporte/pendencias': typeof SuportePendenciasRoute
  '/_suporte/rotinas': typeof SuporteRotinasRoute
  '/questionario/$id': typeof QuestionarioIdRoute
  '/_comercial/diagnosticos/$id': typeof ComercialDiagnosticosIdRoute
  '/_comercial/empresas/$id': typeof ComercialEmpresasIdRoute
  '/_comercial/proposta/$id': typeof ComercialPropostaIdRoute
  '/_suporte/cadastros/modulos-eros': typeof SuporteCadastrosModulosErosRoute
  '/_suporte/cadastros/modulos-venux': typeof SuporteCadastrosModulosVenuxRoute
  '/_suporte/cadastros/setores': typeof SuporteCadastrosSetoresRoute
  '/_suporte/cadastros/tickets': typeof SuporteCadastrosTicketsRoute
  '/_suporte/clientes/$id': typeof SuporteClientesIdRoute
  '/_comercial/diagnosticos/': typeof ComercialDiagnosticosIndexRoute
  '/_comercial/empresas/': typeof ComercialEmpresasIndexRoute
  '/_comercial/leads/': typeof ComercialLeadsIndexRoute
  '/_suporte/clientes/': typeof SuporteClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/modulos'
    | '/privacidade'
    | '/register'
    | '/termos'
    | '/agenda'
    | '/configuracoes'
    | '/contatos'
    | '/convites'
    | '/dashboard'
    | '/historico'
    | '/orcamento-avulso'
    | '/pipeline'
    | '/relatorios'
    | '/usuarios-config'
    | '/ajustes'
    | '/chamados'
    | '/metricas'
    | '/painel'
    | '/pendencias'
    | '/rotinas'
    | '/questionario/$id'
    | '/diagnosticos/$id'
    | '/empresas/$id'
    | '/proposta/$id'
    | '/cadastros/modulos-eros'
    | '/cadastros/modulos-venux'
    | '/cadastros/setores'
    | '/cadastros/tickets'
    | '/clientes/$id'
    | '/diagnosticos/'
    | '/empresas/'
    | '/leads/'
    | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/modulos'
    | '/privacidade'
    | '/register'
    | '/termos'
    | '/agenda'
    | '/configuracoes'
    | '/contatos'
    | '/convites'
    | '/dashboard'
    | '/historico'
    | '/orcamento-avulso'
    | '/pipeline'
    | '/relatorios'
    | '/usuarios-config'
    | '/ajustes'
    | '/chamados'
    | '/metricas'
    | '/painel'
    | '/pendencias'
    | '/rotinas'
    | '/questionario/$id'
    | '/diagnosticos/$id'
    | '/empresas/$id'
    | '/proposta/$id'
    | '/cadastros/modulos-eros'
    | '/cadastros/modulos-venux'
    | '/cadastros/setores'
    | '/cadastros/tickets'
    | '/clientes/$id'
    | '/diagnosticos'
    | '/empresas'
    | '/leads'
    | '/clientes'
  id:
    | '__root__'
    | '/'
    | '/_comercial'
    | '/_suporte'
    | '/forgot-password'
    | '/login'
    | '/modulos'
    | '/privacidade'
    | '/register'
    | '/termos'
    | '/_comercial/agenda'
    | '/_comercial/configuracoes'
    | '/_comercial/contatos'
    | '/_comercial/convites'
    | '/_comercial/dashboard'
    | '/_comercial/historico'
    | '/_comercial/orcamento-avulso'
    | '/_comercial/pipeline'
    | '/_comercial/relatorios'
    | '/_comercial/usuarios-config'
    | '/_suporte/ajustes'
    | '/_suporte/chamados'
    | '/_suporte/metricas'
    | '/_suporte/painel'
    | '/_suporte/pendencias'
    | '/_suporte/rotinas'
    | '/questionario/$id'
    | '/_comercial/diagnosticos/$id'
    | '/_comercial/empresas/$id'
    | '/_comercial/proposta/$id'
    | '/_suporte/cadastros/modulos-eros'
    | '/_suporte/cadastros/modulos-venux'
    | '/_suporte/cadastros/setores'
    | '/_suporte/cadastros/tickets'
    | '/_suporte/clientes/$id'
    | '/_comercial/diagnosticos/'
    | '/_comercial/empresas/'
    | '/_comercial/leads/'
    | '/_suporte/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComercialRoute: typeof ComercialRouteWithChildren
  SuporteRoute: typeof SuporteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ModulosRoute: typeof ModulosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RegisterRoute: typeof RegisterRoute
  TermosRoute: typeof TermosRoute
  QuestionarioIdRoute: typeof QuestionarioIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_comercial': {
      id: '/_comercial'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_suporte': {
      id: '/_suporte'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos': {
      id: '/modulos'
      path: '/modulos'
      fullPath: '/modulos'
      preLoaderRoute: typeof ModulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_comercial/agenda': {
      id: '/_comercial/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof ComercialAgendaRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/_comercial/configuracoes': {
      id: '/_comercial/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ComercialConfiguracoesRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/_comercial/contatos': {
      id: '/_comercial/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof ComercialContatosRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/_comercial/convites': {
      id: '/_comercial/convites'
      path: '/convites'
      fullPath: '/convites'
      preLoaderRoute: typeof ComercialConvitesRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/_comercial/dashboard': {
      id: '/_comercial/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ComercialDashboardRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/_comercial/historico': {
      id: '/_comercial/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof ComercialHistoricoRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/_comercial/orcamento-avulso': {
      id: '/_comercial/orcamento-avulso'
      path: '/orcamento-avulso'
      fullPath: '/orcamento-avulso'
      preLoaderRoute: typeof ComercialOrcamentoAvulsoRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/_comercial/pipeline': {
      id: '/_comercial/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof ComercialPipelineRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/_comercial/relatorios': {
      id: '/_comercial/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof ComercialRelatoriosRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/_comercial/usuarios-config': {
      id: '/_comercial/usuarios-config'
      path: '/usuarios-config'
      fullPath: '/usuarios-config'
      preLoaderRoute: typeof ComercialUsuariosConfigRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/_suporte/ajustes': {
      id: '/_suporte/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof SuporteAjustesRouteImport
      parentRoute: typeof SuporteRoute
    }
    '/_suporte/chamados': {
      id: '/_suporte/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof SuporteChamadosRouteImport
      parentRoute: typeof SuporteRoute
    }
    '/_suporte/metricas': {
      id: '/_suporte/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof SuporteMetricasRouteImport
      parentRoute: typeof SuporteRoute
    }
    '/_suporte/painel': {
      id: '/_suporte/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof SuportePainelRouteImport
      parentRoute: typeof SuporteRoute
    }
    '/_suporte/pendencias': {
      id: '/_suporte/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof SuportePendenciasRouteImport
      parentRoute: typeof SuporteRoute
    }
    '/_suporte/rotinas': {
      id: '/_suporte/rotinas'
      path: '/rotinas'
      fullPath: '/rotinas'
      preLoaderRoute: typeof SuporteRotinasRouteImport
      parentRoute: typeof SuporteRoute
    }
    '/questionario/$id': {
      id: '/questionario/$id'
      path: '/questionario/$id'
      fullPath: '/questionario/$id'
      preLoaderRoute: typeof QuestionarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_comercial/diagnosticos/': {
      id: '/_comercial/diagnosticos/'
      path: '/diagnosticos'
      fullPath: '/diagnosticos/'
      preLoaderRoute: typeof ComercialDiagnosticosIndexRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/_comercial/diagnosticos/$id': {
      id: '/_comercial/diagnosticos/$id'
      path: '/diagnosticos/$id'
      fullPath: '/diagnosticos/$id'
      preLoaderRoute: typeof ComercialDiagnosticosIdRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/_comercial/empresas/': {
      id: '/_comercial/empresas/'
      path: '/empresas'
      fullPath: '/empresas/'
      preLoaderRoute: typeof ComercialEmpresasIndexRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/_comercial/empresas/$id': {
      id: '/_comercial/empresas/$id'
      path: '/empresas/$id'
      fullPath: '/empresas/$id'
      preLoaderRoute: typeof ComercialEmpresasIdRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/_comercial/leads/': {
      id: '/_comercial/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof ComercialLeadsIndexRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/_comercial/proposta/$id': {
      id: '/_comercial/proposta/$id'
      path: '/proposta/$id'
      fullPath: '/proposta/$id'
      preLoaderRoute: typeof ComercialPropostaIdRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/_suporte/cadastros/modulos-eros': {
      id: '/_suporte/cadastros/modulos-eros'
      path: '/cadastros/modulos-eros'
      fullPath: '/cadastros/modulos-eros'
      preLoaderRoute: typeof SuporteCadastrosModulosErosRouteImport
      parentRoute: typeof SuporteRoute
    }
    '/_suporte/cadastros/modulos-venux': {
      id: '/_suporte/cadastros/modulos-venux'
      path: '/cadastros/modulos-venux'
      fullPath: '/cadastros/modulos-venux'
      preLoaderRoute: typeof SuporteCadastrosModulosVenuxRouteImport
      parentRoute: typeof SuporteRoute
    }
    '/_suporte/cadastros/setores': {
      id: '/_suporte/cadastros/setores'
      path: '/cadastros/setores'
      fullPath: '/cadastros/setores'
      preLoaderRoute: typeof SuporteCadastrosSetoresRouteImport
      parentRoute: typeof SuporteRoute
    }
    '/_suporte/cadastros/tickets': {
      id: '/_suporte/cadastros/tickets'
      path: '/cadastros/tickets'
      fullPath: '/cadastros/tickets'
      preLoaderRoute: typeof SuporteCadastrosTicketsRouteImport
      parentRoute: typeof SuporteRoute
    }
    '/_suporte/clientes/': {
      id: '/_suporte/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof SuporteClientesIndexRouteImport
      parentRoute: typeof SuporteRoute
    }
    '/_suporte/clientes/$id': {
      id: '/_suporte/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof SuporteClientesIdRouteImport
      parentRoute: typeof SuporteRoute
    }
  }
}

interface ComercialRouteChildren {
  ComercialAgendaRoute: typeof ComercialAgendaRoute
  ComercialConfiguracoesRoute: typeof ComercialConfiguracoesRoute
  ComercialContatosRoute: typeof ComercialContatosRoute
  ComercialConvitesRoute: typeof ComercialConvitesRoute
  ComercialDashboardRoute: typeof ComercialDashboardRoute
  ComercialHistoricoRoute: typeof ComercialHistoricoRoute
  ComercialOrcamentoAvulsoRoute: typeof ComercialOrcamentoAvulsoRoute
  ComercialPipelineRoute: typeof ComercialPipelineRoute
  ComercialRelatoriosRoute: typeof ComercialRelatoriosRoute
  ComercialUsuariosConfigRoute: typeof ComercialUsuariosConfigRoute
  ComercialDiagnosticosIdRoute: typeof ComercialDiagnosticosIdRoute
  ComercialEmpresasIdRoute: typeof ComercialEmpresasIdRoute
  ComercialPropostaIdRoute: typeof ComercialPropostaIdRoute
  ComercialDiagnosticosIndexRoute: typeof ComercialDiagnosticosIndexRoute
  ComercialEmpresasIndexRoute: typeof ComercialEmpresasIndexRoute
  ComercialLeadsIndexRoute: typeof ComercialLeadsIndexRoute
}

const ComercialRouteChildren: ComercialRouteChildren = {
  ComercialAgendaRoute: ComercialAgendaRoute,
  ComercialConfiguracoesRoute: ComercialConfiguracoesRoute,
  ComercialContatosRoute: ComercialContatosRoute,
  ComercialConvitesRoute: ComercialConvitesRoute,
  ComercialDashboardRoute: ComercialDashboardRoute,
  ComercialHistoricoRoute: ComercialHistoricoRoute,
  ComercialOrcamentoAvulsoRoute: ComercialOrcamentoAvulsoRoute,
  ComercialPipelineRoute: ComercialPipelineRoute,
  ComercialRelatoriosRoute: ComercialRelatoriosRoute,
  ComercialUsuariosConfigRoute: ComercialUsuariosConfigRoute,
  ComercialDiagnosticosIdRoute: ComercialDiagnosticosIdRoute,
  ComercialEmpresasIdRoute: ComercialEmpresasIdRoute,
  ComercialPropostaIdRoute: ComercialPropostaIdRoute,
  ComercialDiagnosticosIndexRoute: ComercialDiagnosticosIndexRoute,
  ComercialEmpresasIndexRoute: ComercialEmpresasIndexRoute,
  ComercialLeadsIndexRoute: ComercialLeadsIndexRoute,
}

const ComercialRouteWithChildren = ComercialRoute._addFileChildren(
  ComercialRouteChildren,
)

interface SuporteRouteChildren {
  SuporteAjustesRoute: typeof SuporteAjustesRoute
  SuporteChamadosRoute: typeof SuporteChamadosRoute
  SuporteMetricasRoute: typeof SuporteMetricasRoute
  SuportePainelRoute: typeof SuportePainelRoute
  SuportePendenciasRoute: typeof SuportePendenciasRoute
  SuporteRotinasRoute: typeof SuporteRotinasRoute
  SuporteCadastrosModulosErosRoute: typeof SuporteCadastrosModulosErosRoute
  SuporteCadastrosModulosVenuxRoute: typeof SuporteCadastrosModulosVenuxRoute
  SuporteCadastrosSetoresRoute: typeof SuporteCadastrosSetoresRoute
  SuporteCadastrosTicketsRoute: typeof SuporteCadastrosTicketsRoute
  SuporteClientesIdRoute: typeof SuporteClientesIdRoute
  SuporteClientesIndexRoute: typeof SuporteClientesIndexRoute
}

const SuporteRouteChildren: SuporteRouteChildren = {
  SuporteAjustesRoute: SuporteAjustesRoute,
  SuporteChamadosRoute: SuporteChamadosRoute,
  SuporteMetricasRoute: SuporteMetricasRoute,
  SuportePainelRoute: SuportePainelRoute,
  SuportePendenciasRoute: SuportePendenciasRoute,
  SuporteRotinasRoute: SuporteRotinasRoute,
  SuporteCadastrosModulosErosRoute: SuporteCadastrosModulosErosRoute,
  SuporteCadastrosModulosVenuxRoute: SuporteCadastrosModulosVenuxRoute,
  SuporteCadastrosSetoresRoute: SuporteCadastrosSetoresRoute,
  SuporteCadastrosTicketsRoute: SuporteCadastrosTicketsRoute,
  SuporteClientesIdRoute: SuporteClientesIdRoute,
  SuporteClientesIndexRoute: SuporteClientesIndexRoute,
}

const SuporteRouteWithChildren =
  SuporteRoute._addFileChildren(SuporteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComercialRoute: ComercialRouteWithChildren,
  SuporteRoute: SuporteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ModulosRoute: ModulosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RegisterRoute: RegisterRoute,
  TermosRoute: TermosRoute,
  QuestionarioIdRoute: QuestionarioIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
